### ISSUE TITLE
申请加入开发团队

### ISSUE THREAD

**Issue by Ezgx** [LingmoOS/LingmoOS-Release#1]
![image](https://user-images.githubusercontent.com/110729988/230702753-6880df36-0ac5-4e3c-8dd5-07913043a411.png)
有html，css开发经验

**Comment by Ezgx** [comment]
QQ3387251845，在用户群里

**Comment by ybh618** [comment]
加我一个，我QQ2286848192，会一点C++

**Comment by Lingmo-dev** [comment]
发送邀请了哈

**Comment by devcxl** [comment]
Python、Shell、HTML&CSS，或许能提供一些帮助。希望能加入开发团队。

**Comment by ganyuanzhen** [comment]
目前是电子信息工程类大三（社区里的elysia）。学习过JS，TS,Qt，C#，Unity，Cocos和电路设计（bushi。同时我的英语水平也挺可以的（大概吧

希望可以加入~

**Comment by lingmo-dream** [comment]
> 目前是电子信息工程类大三（社区里的elysia）。学习过C/C++，Python,JS，TS, Qt，C#，Unity，Cocos和电路设计（bushi。同时我的英语水平也挺可以的（大概吧
> 
> 希望可以加入~
> 
> 一些参考仓库
> 
> https://github.com/ganyuanzhen/TXT-Automatic-Chaptering
> 
> https://github.com/Linux-Multi-Architecture-Store/SWJTU-Calendar
> 
> https://gitcode.com/weixin_46341175/SynoMusic

已发送邀请

**Comment by zhendewokusi** [comment]
你好，我是一名大二在校学生，有C，C++，Linux系统编程网络编程基础。
希望可以加入~

qq:768672249

**Comment by lingmo-dream** [comment]
> 你好，我是一名在校大二学生，有C，C++，Linux系统编程网络编程基础。 希望可以加入~
> 
> QQ:768672249

已发送邀请

**Comment by elysia-best** [comment]
关闭这个issue了
