### ISSUE TITLE
LingmoOS-2.0-Polaris-beta3-desktop-amd64密码问题

### ISSUE THREAD

**Issue by lldxlzy** [LingmoOS/LingmoOS-Release#9]
LingmoOS-2.0-Polaris-beta3-desktop-amd64密码不是LiveCD
求密吗

**Comment by walterfang1209** [comment]
> LingmoOS-2.0-Polaris-beta3-desktop-amd64密码不是LiveCD 求密吗

密码为 `live`。另外强烈建议您阅读~新鲜出炉的~[文档](https://lingmo-documentation.vercel.app/zh/)！
